codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "75...90"

status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false

ignore:
  - "api/src/main/java/org/openmrs/module/procedure/Procedure.java"
