codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "75...90"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  - "api/src/main/java/org/openmrs/module/procedure/Procedure.java"
  - "api/src/main/java/org/openmrs/module/procedure/api/ProcedureService.java"
  - "api/src/main/java/org/openmrs/module/procedure/api/dao/ProcedureDao.java"
  - "api/src/main/java/org/openmrs/module/procedure/api/impl/ProcedureServiceImpl.java"
